export type DataProfessionalObject = {
    uid: string;
    idType: string;
    id: string;
    name: string;
    lastName: string;
    phone: any;
    phone2: any;
    address: string;
    country: string;
    state: any;
    city: string;
    email: string;
    password: string;
    confirmPassword: string;
    specialty: string;
    contract: string;
    rol: string;
    urlPhoto: string;
    timestamp: Date;
    isActive: boolean;
    isDeleted: boolean;
};
